### ISSUE TITLE
Only showing images set with android:src attribute

### ISSUE THREAD

**Issue by tpfaff** [gjiazhe/PanoramaImageView#1]
I'm trying to have all of my viewholders in a recyclerview use the same gyroscopeobserver instance. I set the observer in the onCreateViewHolder method. I load an image into the imageview in the viewholder with picasso. My images don't show up, it's just black. Images are loading fine with a standard imageview. If i set a static image using the android:src attribute, everything is working fine.

**Comment by gjiazhe** [comment]
I tried it just now, but it works well for me with Picasso .
Please give me the sample code if possible.
Thanks.

**Comment by tpfaff** [comment]
Thanks, I'll get you a sample tomorrow.

**Comment by gjiazhe** [comment]
Hi, @tpfaff.
Do you solved this?
I'll close this issue because the lib works well for me with Picasso.
If you still have problems, comment again.
Thanks for using this library.
