### ISSUE TITLE
仅6.0上有用？

### ISSUE THREAD

**Issue by LiuYoung628** [gjiazhe/PanoramaImageView#10]
这边一台MEIZU MX6 6.0 可以，但是 ZTE BA601 5.1不行耶

**Comment by gjiazhe** [comment]
Demo 也无法运行么？请描述一下具体的问题

**Comment by LiuYoung628** [comment]
对的，demo也无法运行，piv_show_scrollbar可见，但是晃动手机无效果

**Comment by gjiazhe** [comment]
ZTE BA601 没有陀螺仪传感器，所以不支持
