### ISSUE TITLE
not working PanoramaImageView

### ISSUE THREAD

**Issue by SaurabhGaddelpalliwar** [gjiazhe/PanoramaImageView#11]
PanoramaImageView not working in api level 21 (lolipop) why?

**Comment by codernavi18** [comment]
Did you face any error or crash?
And does your device support Gyroscope sensor? (Because the current HEAD supports only Gyroscope sensor. You can use my pull request to test, which supports accelerometer sensor as well)

**Comment by SaurabhGaddelpalliwar** [comment]
yes you are right, my device not  support Gyroscope sensor,


thanks

**Comment by codernavi18** [comment]
Can you please mark the issue as closed?
