### ISSUE TITLE
Hotspot

### ISSUE THREAD

**Issue by s1mar** [gjiazhe/PanoramaImageView#6]
does this have a provision for adding hotposts(hostspot functionality)?!?

**Comment by gjiazhe** [comment]
What is hotposts(hostspot functionality) ?

**Comment by s1mar** [comment]
The ability to Overlay interactable markers at certain points in the panoramic image

**Comment by gjiazhe** [comment]
No, it doesn't. There are too many things to be considered in this case, for example, the markers' positions, how the markers look like, what the interaction mode is(click, drag), etc. To avoid high coupling, it's not ImageView's responsibility to control all these. I think you should create another view to do this.
