### ISSUE TITLE
Classes won't work 

### ISSUE THREAD

**Issue by TassiloHeinrich** [gjiazhe/PanoramaImageView#8]
Two of the classes won't work. The PanoramaImageView and GyroscopeObserver. They can't resolve the ImageView in public class [classname] extends ImageView and they both have an error that says 

'addPanoramaImageView(com.gjiazhe.panoramaimageview.PanoramaImageView)' is not public in 'com.gjiazhe.panoramaimageview.GyroscopeObserver'. Cannot be accessed from outside package

**Comment by gjiazhe** [comment]
Why do you use this function "addPanoramaImageView"
